from pathlib import Path
p=Path('/mnt/data/reptrack_v9')
s=(p/'script.js').read_text()
insert='''\nconst ICON_OPTIONS = [\n  ['icons/push-up.svg','Віджимання'], ['icons/pull-up.svg','Підтягування'],\n  ['icons/diamond.svg','Алмаз'], ['icons/wide.svg','Широкий хват'],\n  ['icons/incline.svg','Від опори'], ['icons/shoulders.svg','Плечі'],\n  ['icons/abs.svg','Прес'], ['icons/legs.svg','Ноги'],\n  ['icons/neck.svg','Шия'], ['icons/stretch.svg','Розтяжка'],\n  ['icons/cardio.svg','Кардіо'], ['icons/custom.svg','Інше']\n];\n\nfunction iconHtml(value, cls='icon-image') {\n  const v = String(value || '');\n  if (v.endsWith('.svg') || v.includes('/')) return `<img class="${cls}" src="${escapeHtml(v)}" alt="" draggable="false">`;\n  return escapeHtml(v || '✦');\n}\n\nfunction populateIconPicker(containerId, inputId, selectedValue='icons/custom.svg') {\n  const root = document.getElementById(containerId);\n  const input = document.getElementById(inputId);\n  if (!root || !input) return;\n  input.value = selectedValue || 'icons/custom.svg';\n  root.innerHTML = ICON_OPTIONS.map(([src,label]) => `<button type="button" class="icon-choice ${src===input.value?'selected':''}" data-icon-value="${src}" title="${escapeHtml(label)}"><img src="${src}" alt="${escapeHtml(label)}" draggable="false"><span>${escapeHtml(label)}</span></button>`).join('');\n  root.querySelectorAll('[data-icon-value]').forEach(btn => btn.addEventListener('click', () => {\n    input.value = btn.dataset.iconValue;\n    root.querySelectorAll('.icon-choice').forEach(x => x.classList.toggle('selected', x===btn));\n  }));\n}\n'''
s=s.replace("const DEFAULT_EXERCISES = [", insert+"\nconst DEFAULT_EXERCISES = [",1)
# Load settings add offline flag? no.
# Replace setupMobileUX end add visibility and network\ns=s.replace("""  window.addEventListener('orientationchange', () => setTimeout(() => document.documentElement.style.setProperty('--app-height', `${window.innerHeight}px`), 150));\n  setupLiquidNav(isIPhone);\n}""", """  window.addEventListener('orientationchange', () => setTimeout(() => document.documentElement.style.setProperty('--app-height', `${window.innerHeight}px`), 150));\n  const syncNetwork = () => { const el = $('#network-status'); if (!el) return; el.textContent = navigator.onLine ? 'Онлайн' : 'Офлайн · дані збережено'; el.classList.toggle('offline', !navigator.onLine); };\n  window.addEventListener('online', syncNetwork); window.addEventListener('offline', syncNetwork); syncNetwork();\n  document.addEventListener('visibilitychange', () => { if (!document.hidden) { state.selectedDate = localDateKey(); state.calendarDate = new Date(); renderAll(); } });\n  window.addEventListener('pageshow', () => { state.selectedDate = localDateKey(); state.calendarDate = new Date(); renderAll(); });\n  setupLiquidNav(isIPhone);\n}""",1)
# showScreen auto today home\ns=s.replace("""function showScreen(name) {\n  state.currentScreen = name;\n""", """function showScreen(name) {\n  state.currentScreen = name;\n  if (name === 'home') { state.selectedDate = localDateKey(); state.calendarDate = new Date(); }\n""",1)
# builder bind picker initialization\ns=s.replace("""  $('#save-category').addEventListener('click', createCategory);\n  $('#save-exercise').addEventListener('click', createExercise);\n}""", """  $('#save-category').addEventListener('click', createCategory);\n  $('#save-exercise').addEventListener('click', createExercise);\n  populateIconPicker('category-icon-picker','category-icon');\n  populateIconPicker('exercise-icon-picker','exercise-icon');\n  $('#history-close').addEventListener('click', closeHistoryModal);\n  $('#history-modal').addEventListener('click', e => { if (e.target.id === 'history-modal') closeHistoryModal(); });\n}""",1)
# setBuilderMode populate pickers resets default only when form opened? leave selected.
s=s.replace("""  if (mode === 'exercise') fillExerciseCategorySelect();\n}""", """  if (mode === 'exercise') fillExerciseCategorySelect();\n  populateIconPicker('category-icon-picker','category-icon', $('#category-icon')?.value || 'icons/custom.svg');\n  populateIconPicker('exercise-icon-picker','exercise-icon', $('#exercise-icon')?.value || 'icons/custom.svg');\n}""",1)
# create category/exercise remove text clear, set defaults\ns=s.replace("""  $('#category-icon').value = '';\n""", """  populateIconPicker('category-icon-picker','category-icon','icons/custom.svg');\n""",1)
s=s.replace("""  $('#exercise-icon').value = '';\n""", """  populateIconPicker('exercise-icon-picker','exercise-icon','icons/custom.svg');\n""",1)
# Render icon in home
s=s.replace("<div class=\"exercise-icon\">${escapeHtml(exercise.icon || '✦')}</div>", "<div class=\"exercise-icon\">${iconHtml(exercise.icon || '✦')}</div>")
# Render exercise section icons and row icons
s=s.replace("<span class=\"section-icon\">${escapeHtml(category.icon || '◉')}</span>", "<span class=\"section-icon\">${iconHtml(category.icon || '◉')}</span>")
s=s.replace("<span class=\"row-icon\">${escapeHtml(ex.icon || '✦')}</span>", "<span class=\"row-icon\">${iconHtml(ex.icon || '✦')}</span>")
# Add history button in menu
s=s.replace("""  menu.innerHTML = `\n    <button data-menu-log>＋ Додати повторення</button>\n    <button class=\"danger-menu\" data-menu-delete>🗑 Видалити вправу</button>`;""", """  menu.innerHTML = `\n    <button data-menu-log>＋ Додати повторення</button>\n    <button data-menu-history>↗ Історія вправи</button>\n    <button class=\"danger-menu\" data-menu-delete>🗑 Видалити вправу</button>`;""",1)
s=s.replace("""  menu.querySelector('[data-menu-log]').addEventListener('click', () => {\n    closeExerciseMenu();\n    openLogModal(ex);\n  });\n""", """  menu.querySelector('[data-menu-log]').addEventListener('click', () => {\n    closeExerciseMenu();\n    openLogModal(ex);\n  });\n  menu.querySelector('[data-menu-history]').addEventListener('click', () => {\n    closeExerciseMenu();\n    openExerciseHistory(ex.id);\n  });\n""",1)
# Replace deleteLogEntry with undo version
old='''function deleteLogEntry(exerciseId,date) {\n  const ex=exerciseById(exerciseId); if(!ex || !state.logs[date]?.[exerciseId]) return;\n  delete state.logs[date][exerciseId];\n  if(!Object.keys(state.logs[date]).length) delete state.logs[date];\n  saveLogs(); renderAll(); toast('Запис видалено');\n}\n'''
new='''let lastDeletedLog = null;\nfunction deleteLogEntry(exerciseId,date) {\n  const ex=exerciseById(exerciseId); const reps = Number(state.logs[date]?.[exerciseId] || 0); if(!ex || !reps) return;\n  lastDeletedLog = { exerciseId, date, reps };\n  delete state.logs[date][exerciseId];\n  if(!Object.keys(state.logs[date]).length) delete state.logs[date];\n  saveLogs(); renderAll();\n  toastWithAction('Запис видалено', 'Скасувати', undoDelete);\n}\nfunction undoDelete() {\n  if (!lastDeletedLog) return;\n  const { exerciseId, date, reps } = lastDeletedLog;\n  if (!state.logs[date]) state.logs[date] = {};\n  state.logs[date][exerciseId] = reps;\n  saveLogs(); renderAll(); lastDeletedLog = null; toast('Запис повернуто');\n}\n'''
s=s.replace(old,new)
# Add history before renderSummary
marker='function renderSummary() {'
history_fn='''function openExerciseHistory(exerciseId) {\n  const ex = exerciseById(exerciseId); if (!ex) return;\n  const cat = categoryById(ex.categoryId);\n  $('#history-title').textContent = ex.name;\n  $('#history-subtitle').textContent = `${cat?.name || 'Вправа'} · історія повторень`;\n  const records = Object.entries(state.logs).map(([date, day]) => ({ date, reps: Number(day?.[exerciseId] || 0) })).filter(x => x.reps > 0).sort((a,b) => b.date.localeCompare(a.date));\n  const total = records.reduce((s,x)=>s+x.reps,0);\n  const best = records.reduce((m,x)=>Math.max(m,x.reps),0);\n  const avg = records.length ? Math.round(total / records.length) : 0;\n  $('#history-stats').innerHTML = `<div><b>${total.toLocaleString('uk-UA')}</b><small>всього</small></div><div><b>${best}</b><small>рекорд за день</small></div><div><b>${avg}</b><small>середнє</small></div>`;\n  $('#history-list').innerHTML = records.length ? records.map(x => `<button class="history-row" data-history-date="${x.date}"><span>${escapeHtml(formatFullDate(x.date))}</span><strong>${x.reps}</strong></button>`).join('') : '<div class="empty-inline">Для цієї вправи ще немає записів.</div>';\n  $('#history-list').querySelectorAll('[data-history-date]').forEach(btn => btn.addEventListener('click', () => { state.selectedDate = btn.dataset.historyDate; state.calendarDate = parseDate(btn.dataset.historyDate); closeHistoryModal(); showScreen('calendar'); }));\n  $('#history-modal').classList.remove('hidden');\n}\nfunction closeHistoryModal() { $('#history-modal').classList.add('hidden'); }\n\n'''
s=s.replace(marker,history_fn+marker,1)
# replace toast fn with toastWithAction
oldtoast='''function toast(text) {\n  const existing=$('.toast'); if(existing) existing.remove();\n  const el=document.createElement('div'); el.className='toast'; el.textContent=text; document.body.appendChild(el);\n  requestAnimationFrame(()=>el.classList.add('show')); setTimeout(()=>{el.classList.remove('show');setTimeout(()=>el.remove(),220);},1800);\n}\n'''
newtoast='''function toast(text) {\n  toastWithAction(text, null, null, 1800);\n}\nfunction toastWithAction(text, actionLabel, actionFn, duration=4500) {\n  const existing=$('.toast'); if(existing) existing.remove();\n  const el=document.createElement('div'); el.className='toast';\n  el.innerHTML = `<span>${escapeHtml(text)}</span>${actionLabel ? `<button type="button" class="toast-action">${escapeHtml(actionLabel)}</button>` : ''}`;\n  document.body.appendChild(el);\n  if (actionLabel) el.querySelector('.toast-action').addEventListener('click', () => { actionFn?.(); el.remove(); });\n  requestAnimationFrame(()=>el.classList.add('show')); setTimeout(()=>{el.classList.remove('show');setTimeout(()=>el.remove(),220);},duration);\n}\n'''
s=s.replace(oldtoast,newtoast,1)
# Add drag handlers in renderExercises after button listeners
needle="""  $$('#exercise-sections [data-section-menu]').forEach(btn => btn.addEventListener('click', (e) => { e.stopPropagation(); openCategoryMenu(btn.dataset.sectionMenu, btn); }));\n  $('#restore-defaults-inline')?.addEventListener('click', restoreDefaultLibrary);\n}"""
replacement="""  $$('#exercise-sections [data-section-menu]').forEach(btn => btn.addEventListener('click', (e) => { e.stopPropagation(); openCategoryMenu(btn.dataset.sectionMenu, btn); }));\n  bindDragDrop();\n  $('#restore-defaults-inline')?.addEventListener('click', restoreDefaultLibrary);\n}\n\nfunction bindDragDrop() {\n  $$('#exercise-sections .exercise-section').forEach(section => {\n    section.draggable = true;\n    section.addEventListener('dragstart', e => { e.dataTransfer.setData('text/category', section.dataset.category); section.classList.add('dragging'); });\n    section.addEventListener('dragend', () => section.classList.remove('dragging'));\n    section.addEventListener('dragover', e => e.preventDefault());\n    section.addEventListener('drop', e => {\n      e.preventDefault();\n      const id = e.dataTransfer.getData('text/category'); if (!id || id === section.dataset.category) return;\n      const from = state.categories.findIndex(c=>c.id===id), to = state.categories.findIndex(c=>c.id===section.dataset.category); if (from<0 || to<0) return;\n      const [moved] = state.categories.splice(from,1); state.categories.splice(to,0,moved); persistLibrary(); renderExercises();\n      toast('Розділи впорядковано');\n    });\n  });\n  $$('#exercise-sections .exercise-row').forEach(row => {\n    row.draggable = true;\n    row.addEventListener('dragstart', e => { e.dataTransfer.setData('text/exercise', row.querySelector('[data-log-id]')?.dataset.logId || ''); row.classList.add('dragging'); });\n    row.addEventListener('dragend', () => row.classList.remove('dragging'));\n    row.addEventListener('dragover', e => e.preventDefault());\n    row.addEventListener('drop', e => {\n      e.preventDefault();\n      const movingId = e.dataTransfer.getData('text/exercise'); const targetId = row.querySelector('[data-log-id]')?.dataset.logId; if(!movingId || !targetId || movingId===targetId) return;\n      const moving = exerciseById(movingId), target = exerciseById(targetId); if(!moving || !target || moving.categoryId !== target.categoryId) return;\n      const same = state.exercises.filter(x=>x.categoryId===moving.categoryId); const from = same.findIndex(x=>x.id===movingId), to = same.findIndex(x=>x.id===targetId);\n      const ids = same.map(x=>x.id); const [id] = ids.splice(from,1); ids.splice(to,0,id);\n      const reordered=[]; ids.forEach(i=>reordered.push(exerciseById(i)));\n      const rest=state.exercises.filter(x=>x.categoryId!==moving.categoryId);\n      const firstIndex=Math.min(...state.exercises.map((x,i)=>x.categoryId===moving.categoryId?i:999999));\n      rest.splice(firstIndex===999999?rest.length:firstIndex,0,...reordered);\n      state.exercises=rest; persistLibrary(); renderExercises(); toast('Вправи впорядковано');\n    });\n  });\n}"""
s=s.replace(needle,replacement,1)
# Heatmap replace whole function by locating start/end
start=s.index('function renderHeatmap() {')
end=s.index('function renderDayDetail() {', start)
new_heat='''function renderHeatmap() {\n  const grid = $('#heatmap-grid'); const months = $('#heatmap-months'); const totalBadge = $('#heatmap-total');\n  if (!grid || !months || !totalBadge) return;\n  const end = new Date(state.selectedDate + 'T12:00:00');\n  const start = new Date(end); start.setDate(start.getDate() - 90);\n  const monday = new Date(start); monday.setDate(monday.getDate() - ((monday.getDay()+6)%7));\n  const totalDays = 13 * 7;\n  const cells=[]; let total=0; const monthLabels=[]; let lastMonth=-1;\n  for(let i=0;i<totalDays;i++){\n    const d=new Date(monday); d.setDate(monday.getDate()+i); const key=localDateKey(d); const reps=dayTotal(key); total+=reps;\n    const goal=Math.max(1,Number(state.settings.dailyGoal||50));\n    const ratio=reps/goal;\n    const level=reps===0?0:ratio<0.25?1:ratio<0.5?2:ratio<1?3:4;\n    cells.push({key,reps,level,d});\n    if(d.getDate()<=7 && d.getMonth()!==lastMonth){ lastMonth=d.getMonth(); monthLabels.push({col:Math.floor(i/7)+1,label:d.toLocaleDateString('uk-UA',{month:'short'}).replace('.','')}); }\n  }\n  grid.innerHTML=cells.map(c=>`<button class="heatmap-cell level-${c.level} ${c.key===state.selectedDate?'selected':''}" data-date="${c.key}" aria-label="${escapeHtml(formatShortDate(c.key))}: ${c.reps} повторень" title="${escapeHtml(formatShortDate(c.key))}: ${c.reps} повторень"></button>`).join('');\n  months.innerHTML=monthLabels.map(x=>`<span style="grid-column:${x.col}">${escapeHtml(x.label)}</span>`).join('');\n  totalBadge.textContent=total.toLocaleString('uk-UA');\n  $$('#heatmap-grid [data-date]').forEach(cell=>cell.addEventListener('click',()=>{ state.selectedDate=cell.dataset.date; state.calendarDate=parseDate(cell.dataset.date); renderCalendar(); renderHome(); renderExercises(); renderHeatmap(); }));\n}\n\n'''
s=s[:start]+new_heat+s[end:]
# Add history option and make detail rows swipeable by wrapping? We'll alter row HTML minimally
s=s.replace("return `<div class=\"detail-row\"><div><div class=\"detail-name\">", "return `<div class=\"detail-row swipe-row\" data-swipe-id=\"${ex.id}\"><div class=\"swipe-actions\"><button class=\"swipe-edit\" data-swipe-edit=\"${ex.id}\">Редагувати</button><button class=\"swipe-delete\" data-swipe-delete=\"${ex.id}\">Видалити</button></div><div class=\"swipe-content\"><div><div class=\"detail-name\">")
s=s.replace("</div><div class=\"detail-actions\"><button class=\"detail-edit\"", "</div></div><div class=\"detail-actions\"><button class=\"detail-edit\"")
# close swipe-content before final row div in detail mapping: targeted snippet
s=s.replace("</button><button class=\"detail-delete\" data-delete-log=${ex.id} aria-label=\"Видалити запис\">×</button></div></div>".replace('${ex.id}', "${ex.id}"), "</button><button class=\"detail-delete\" data-delete-log=\"${ex.id}\" aria-label=\"Видалити запис\">×</button></div></div></div>")
# That replacement likely fails due escaping; use manual around exact source later.
# Add swipe bind after existing event listeners in renderDayDetail
needle2="""  $$('#day-detail [data-delete-log]').forEach(btn=>btn.addEventListener('click',()=>deleteLogEntry(btn.dataset.deleteLog,state.selectedDate)));\n}"""
rep2="""  $$('#day-detail [data-delete-log]').forEach(btn=>btn.addEventListener('click',()=>deleteLogEntry(btn.dataset.deleteLog,state.selectedDate)));\n  bindSwipeRows();\n}\n\nfunction bindSwipeRows() {\n  $$('#day-detail .swipe-row').forEach(row => {\n    let startX=0, startY=0, moved=false;\n    row.addEventListener('touchstart', e => { const t=e.touches[0]; startX=t.clientX; startY=t.clientY; moved=false; }, {passive:true});\n    row.addEventListener('touchmove', e => { const t=e.touches[0]; const dx=t.clientX-startX, dy=t.clientY-startY; if(Math.abs(dx)>12 && Math.abs(dx)>Math.abs(dy)){ moved=true; row.classList.toggle('swiped', dx < -48); } }, {passive:true});\n    row.addEventListener('touchend', () => { if(!moved) row.classList.remove('swiped'); });\n  });\n  $$('#day-detail [data-swipe-edit]').forEach(btn=>btn.addEventListener('click',()=>{ const ex=exerciseById(btn.dataset.swipeEdit); if(ex) openLogModal(ex); }));\n  $$('#day-detail [data-swipe-delete]').forEach(btn=>btn.addEventListener('click',()=>deleteLogEntry(btn.dataset.swipeDelete,state.selectedDate)));\n}\n"""
s=s.replace(needle2,rep2,1)
(p/'script.js').write_text(s)
